### Intro

In [ ]:
4+5+9-545454-5454+87877*36*651654984984

2061557464155251958

In [ ]:
print(5*3)

15


In [ ]:
print('ciao')

ciao


In [ ]:
x = 34 #INTEGER

In [ ]:
type(x)

int

In [ ]:
x = 34.0 #FLOAT

In [ ]:
type(x)

float

In [ ]:
k = False

In [ ]:
x=a

NameError: name 'a' is not defined

In [ ]:
pippo=5
pippo

5

In [ ]:
pippo*2

10

In [ ]:
#1test          #ERROR
t2453453 = 10
#la variabile=10  #ERROR
#la-variabile=10  #ERROR
la_variabile=10
LaVaRiAbiLe = 12
#Lavariabile = 3
#LAVARIABILE = 4

In [ ]:
#stringa='l'albero'
stringa="l'albero"

stringa # notebook way
#print(stringa) # file python .py way

"l'albero"

In [ ]:
type(stringa)

str

In [ ]:
stringa1 = 'la notte leoni...'
stringa2 = 'la mattina...'

In [ ]:
print(stringa1+stringa2)

la notte leoni...la mattina...


In [ ]:
stringa1*4

'la notte leoni...la notte leoni...la notte leoni...la notte leoni...'

In [ ]:
età=29
testo = 'la mia età è ..'

#errore!

testo+età

TypeError: can only concatenate str (not "int") to str

In [ ]:
testo+str(età)

'la mia età è ..29'

In [ ]:
type(età)

int

In [ ]:
pere = '20'

In [ ]:
type(pere)

str

In [ ]:
# trasformazion in numero:
int(pere)

20

In [ ]:
float(pere)

20.0

In [ ]:
pere*3 ### errore!!!!!!!!!

'202020'

In [ ]:
float(pere)*3

60.0

In [ ]:
aaa = " se questa frase \n è troppo lung"
aaa

' se questa frase \n è troppo lung'

In [ ]:
print(" se questa frase \n è troppo lunga, può \n benissimo essere suddivisa in \n due o più righe!")

 se questa frase 
 è troppo lunga, può 
 benissimo essere suddivisa in 
 due o più righe!


In [ ]:
from google.colab import files
uploaded = files.upload()

KeyboardInterrupt: 

In [ ]:
!pip install calmsize

  Created wheel for calmsize: filename=calmsize-0.1.3-cp36-none-any.whl size=2887 sha256=7c7be09df3aa34a821d8f3f23d3482b01fa2bc707733a68b6460ed39e3801b7a
  Stored in directory: /root/.cache/pip/wheels/02/ac/1a/2a3418bc8f81abda6cd1b6d0f8f287556fc8de80dbabab75d1
Successfully built calmsize


In [ ]:
import calmsize as cs

In [ ]:
cs.size(2048)

2K<ByteSize amount=2.0>

In [ ]:
!pwd  # per printare il percorso su cui ci troviamo
!ls  # per printare la lista delle cartelle che vediamo nell'attuale posizione

/content
sample_data


In [ ]:
!mkdir test

In [ ]:
#!rm -rf test/

In [ ]:
cd test

/content/test


In [ ]:
pwd

'/content/test'

In [ ]:
cd ..


/content


In [ ]:
from IPython.display import Image

#Image('dog.jpg',width=200,height=120)

In [ ]:
Image('https://upload.wikimedia.org/wikipedia/commons/7/74/A-Cat.jpg',width=800,height=450)

Output hidden; open in https://colab.research.google.com to view.

# Titolo

## Categoria

### Subcategoria

####subsubcategoria

'ciao

In [ ]:
# list()--> []
# dict() -->  {}
# tuple() --> ()
# set() --> {}
# array ho bisogno di una libreria esterna= numpy
# pandas

## Oggetti in python

In [ ]:
# [], {},() : LIST -- DICTIONARY -- TUPLE

In [ ]:
## LIST ##

In [ ]:
ciao = 'fdfd'
ciao.upper()

'FDFD'

In [ ]:
lista = [5,9,-2,11]
lista

[5, 9, -2, 11]

In [ ]:
lista.sort()

In [ ]:
lista.sort()
lista

[-2, 5, 9, 11]

In [ ]:
lista.sort(reverse=True)
lista

[11, 9, 5, -2]

In [ ]:
lista = [0,1,-2,3,'hello',1.0,True] # int, string,float
lista

[0, 1, -2, 3, 'hello', 1.0, True]

In [ ]:
type(lista)

list

In [ ]:
len(lista)

7

In [ ]:
lista1 = [3.5*2,2]
lista1

[7.0, 2]

In [ ]:
# generate fast list:
lista1 = [3.5*2,2]*4
lista1

[7.0, 2, 7.0, 2, 7.0, 2, 7.0, 2]

In [ ]:
lista2 = [4]*5
lista2

[4, 4, 4, 4, 4]

In [ ]:
lista2.append(2) # in fondo
lista2

[4, 4, 4, 4, 4, 2]

In [ ]:
lista1 = [1, 2, 3, 4]
lista2 = [5, 6, 7, 8]
lista3 = lista1 + lista2
lista3

[1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
listak = [10, 20, 30, 40]
lista2 = [50, 60, 70, 80]
listak.extend(lista2)
listak

[10, 20, 30, 40, 50, 60, 70, 80]

In [ ]:
#count element inside a list
len(lista2)

4

In [ ]:
#cancellare elemtni lista

anno = [2016, 2017, 2018, 2019 ,2020]

In [ ]:
del anno[-1] ## se lo runno consecutivamente diventa lista vuota
anno

[2016, 2017, 2018, 2019]

In [ ]:
del anno[0:2]
anno

[2018, 2019]

In [ ]:
## oppure nomelista.remove(valore)
anno.remove(2018)
anno

[2019]

In [ ]:
lista = [1,2,3,5,5]
lista

[1, 2, 3, 5, 5]

In [ ]:
len(lista)-1

4

In [ ]:
#select an element of a list
lista[5] # give an ERROR ## list index 0

IndexError: list index out of range

In [ ]:
#lista[0]
#lista[1]
lista[4]

5

In [ ]:
lista[4]==lista[-1]

True

In [ ]:
lista[4]==lista[-2]

True

In [ ]:
primi = [2,3,5,7,11,13,17,19,23,29,31]

In [ ]:
primi[0:] # tutti

[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31]

In [ ]:
primi[4:]

[11, 13, 17, 19, 23, 29, 31]

In [ ]:
primi[4:6]

[11, 13]

In [ ]:
for pippo in primi:
     print(pippo)

2
3
5
7
11
13
17
19
23
29
31


In [ ]:
lista_numerica = list(range(300,400,2))  ## solo numeri pari
lista_numerica

[300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,
 352,
 354,
 356,
 358,
 360,
 362,
 364,
 366,
 368,
 370,
 372,
 374,
 376,
 378,
 380,
 382,
 384,
 386,
 388,
 390,
 392,
 394,
 396,
 398]

In [ ]:
quadrati = []

for n in range(10):
    quadrati.append(n**2)

print(quadrati)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [ ]:
quadrati = [n**2 for n in range(10)]

print(quadrati)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [ ]:
## DICTIONARY ##

In [ ]:
dizionario = {'key':'value'}
dizionario

{'key': 'value'}

In [ ]:
type(dizionario)

dict

In [ ]:
d = {'one':1,'two':2}
d

{'one': 1, 'two': 2}

In [ ]:
d['two']

2

In [ ]:
e = {1:133,2:246}
e

{1: 133, 2: 246}

In [ ]:
f = {'one':1,2:2,3:'three'}
f.values()

dict_values([1, 2, 'three'])

In [ ]:
f.keys()

dict_keys(['one', 2, 3])

In [ ]:
d.values()

dict_values([1, 2])

In [ ]:
data = {
        'anni':[1,3,4,5,6],
        'device':[1,3,4,5,6],
        #'nome':['fdsf','fdsf']
        }
data

{'anni': [1, 3, 4, 5, 6], 'device': [1, 3, 4, 5, 6]}

In [ ]:
import pandas as pd

pd.DataFrame(data)

anni  device
0     1       1
1     3       3
2     4       4
3     5       5
4     6       6

In [ ]:
### TUPLE #### (immutable)

In [ ]:
one = 4,4

In [ ]:
variabile = 45,48
type(variabile)

tuple

In [ ]:
tup1 = (45,1,2,3)
tup2 = (9,4,1)

In [ ]:
tup1

(45, 1, 2, 3)

In [ ]:
tup2

(9, 4, 1)

In [ ]:
 type(tup1)

tuple

In [ ]:
b= sorted(tup2)
b

[1, 4, 9]

In [ ]:
type(b)  # lo trasforma

list

In [ ]:
### convert tuple to list

In [ ]:
lista = [tup1,tup2]
lista

[(45, 1, 2, 3), (9, 4, 1)]

In [ ]:
lista[1] # perchè index 0

(9, 4, 1)

In [ ]:
lista[1][0] #2

9

In [ ]:
lista[1][1] #4

4

In [ ]:
aa = [(45, 1, 2, 3), ([3,4,'ciao',(4,'bau')], 4, 1)]

aa[1][0][-1][1]

'bau'

 #### Array

In [ ]:
import numpy as np

In [ ]:
country = np.array(['USA', 'Japan', 'UK', 'Celestopoli', 'India', 'China'])
country

array(['USA', 'Japan', 'UK', 'Celestopoli', 'India', 'China'],
      dtype='<U11')

In [ ]:
x = np.array([2,3,1,0])
x

array([2, 3, 1, 0])

In [ ]:
x.shape

(4,)

In [ ]:
y = np.array([[2,3,1,0],
              [1,1,1,1],
              ])
y.shape

(2, 4)

In [ ]:
y

array([[2, 3, 1, 0],
       [1, 1, 1, 1]])

In [ ]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
k =np.ones((2, 3))
k

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
k.shape

(2, 3)

In [ ]:
k

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(2, 10, dtype=float) # default strp=1

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [ ]:
x = np.array([3, 6, 9, 12])

In [ ]:
x/3

array([1., 2., 3., 4.])

In [ ]:
print(x)

[ 3  6  9 12]


In [ ]:
type(x)

numpy.ndarray

In [ ]:
z = np.array([2,3,1,0])

In [ ]:
np.sort(z)

array([0, 1, 2, 3])

In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([[9, 8, 7],
              [6, 5, 4]])

In [ ]:
a+b

array([[10, 10, 10],
       [10, 10, 10]])

In [ ]:
c = np.concatenate((a, b))
c

array([[1, 2, 3],
       [4, 5, 6],
       [9, 8, 7],
       [6, 5, 4]])

In [ ]:
c.shape

(4, 3)

In [ ]:
np.ones((2, 2), dtype=bool)

array([[ True,  True],
       [ True,  True]])

In [ ]:
z = np.array([[1, 0, 1], [0, 0, 0]],dtype=bool)
z

array([[ True, False,  True],
       [False, False, False]])

In [ ]:
## Conversion to an array:

import numpy as np
my_list = [1, 2, 3, 4, 5, 6, 7, '8']
my_list = np.asarray(my_list)
#type(my_list)
my_list

array(['1', '2', '3', '4', '5', '6', '7', '8'], dtype='<U21')

In [ ]:
my_tuple = ([8, 4, 6], [1, 2, 3])
type(my_tuple)

tuple

In [ ]:
my_tuple = np.asarray(my_tuple)
my_tuple

array([[8, 4, 6],
       [1, 2, 3]])

#### List vs Tuple

In [ ]:
####### List vs Array
y = [3, 6, 9, 12]
y/3
##Give the error

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [ ]:
# Sorting a list
numbers = [1, 3, 4, 2]
numbers

[1, 3, 4, 2]

In [ ]:
numbers.sort()
print(numbers)

[1, 2, 3, 4]


In [ ]:
## String list
a = ["mela", "banana", "arancia"]
a

['mela', 'banana', 'arancia']

In [ ]:
a[0] = "fragola"
a

['fragola', 'banana', 'arancia']

In [ ]:
type(a)

list

In [ ]:
a = ("mela", "banana", "arancia")
a

('mela', 'banana', 'arancia')

In [ ]:
type(a)

tuple

In [ ]:
a[0] = "fragola"
## Give the error

TypeError: 'tuple' object does not support item assignment

List recap


In [ ]:
a = []
a.append("ciao")

In [ ]:
a.append("a")
a.append("tutti gli")
a.append("studenti")
print("il numero degli elementi all'interno della lista è: ", len(a))

il numero degli elementi all'interno della lista è:  4


In [ ]:
a

['ciao', 'a', 'tutti gli', 'studenti']

In [ ]:
# remove one element from list
a.remove(a[0]) #remove first element 'Hello'
a

['a', 'tutti gli', 'studenti']

In [ ]:
################ Algebra Booleana ###############

In [ ]:
True

True

In [ ]:
False

False

In [ ]:
variabile = True

In [ ]:
type(variabile)

bool

In [ ]:
True + True

2

In [ ]:
45*True

45

In [ ]:
45*False

0

In [ ]:
50>=49.9999

True

In [ ]:
10//2 == 11//2

True

In [ ]:
# vale anche con le stringhe!!

'ciao' != 'goodbye'

True

In [ ]:
'ciao' == 'Ciao'

False

In [ ]:
#######  AND ##############

In [ ]:
5>6 and 6>5

False

In [ ]:
5>4 and 6>7

False

In [ ]:
#######  OR ##############

In [ ]:
25 >=25  or 31!= 31

True

In [ ]:
21 >21 or 31!=31

False

In [ ]:
28!=29 or 33==33

True

In [ ]:
#######  NOT #############

In [ ]:
#negazione

not 3==3

False

In [ ]:
not 2==3

True

 IF example

In [ ]:
età=-5

if età <18:
    print('sei minorenne')
else:
    print('sei maggiorenne')

sei minorenne


In [ ]:
età=18

if età <10:
    print('sei un bimbo')
elif età<=18:
    print('sei un regaz')
elif età<50:
    print('sei un boomer')
else:
    print('bella vecchio! sei anziano')

sei un regaz


In [ ]:
######### caso patente #######

In [ ]:
età=50
patente=False

if età >=18 and patente==True:
    print('puoi guidare finalmente la tua auto da sogno')
elif età >=18 and patente==False:
    print('no patente, no party')
else:
    print('mi dispiace, ritenta quando sarai più grande!!')

no patente, no party


### Scrivi le funzioni

In [10]:
def print_tre_volte_in(x:int,y=3):
    """
    questa funione restituisce l'input stampato 3 volte
    """
    print(x)
    print(x)
    print(x)

In [11]:
print_tre_volte_in('miao')

miao
miao
miao


In [12]:
def print_tre_volte():
    print('Ciao')
    print('il mio nome è')
    print('Daniele')

In [13]:
print_tre_volte()

Ciao
il mio nome è
Daniele


In [14]:
def somma_due_numeri(a,b):
     print('questa funzione somma due numeri:')
     risultato = a + b
     print('il risultato è  '+str(risultato)) # qui è costruito

In [16]:
somma_due_numeri(8,-5)

questa funzione somma due numeri:
il risultato è  3


ALLE FUNZIONI POSSIAMO PASSARE DEI VALORI CHIAMATI ARGOMENTI

In [17]:
def somma_due_numeri(a,b): ## a,b sono argomenti
    #print('questa funzione somma due numeri:')
    risultato = a + b
    return risultato
# OUTPUT DI UNA FUNZIONE è IL VALORE DEL SUO RETURN
# TUTTE LE FUNZIONI HANNO UN RETURN

In [18]:
ris = somma_due_numeri(2,3)
ris

5

In [ ]:
ls

formule.py  __pycache__/  sample_data/


## INPUT

In [ ]:
x =input()
#x = input('inserire qualcosa   ')

hhj


In [ ]:
type(x)

str

In [ ]:
### PROGRAMMA
print('questo è il mio programma in python')

nome=input('inserire il tuo nome  ')
print('buon pomeriggio  '+nome+'  spero tu stia imparando tantissimo!')

questo è il mio programma in python
inserire il tuo nome  tdcyttf
buon pomeriggio  tdcyttf  spero tu stia imparando tantissimo!


In [ ]:
età = input('quanti anni hai?')
print('Bene!!! dunque hai '+ età + '  anni. Il porssimo anno ne avrai '+ str(int(età)+1))

quanti anni hai?3
Bene!!! dunque hai 3  anni. Il porssimo anno ne avrai 4


## Somma due numeri input

In [ ]:
numero1 = float(input('inserisci un primo numero a tua scelta: '))
numero2 = float(input('inserisci un secondo numero a tua scelta: '))

somma = numero1+numero2
print("il risultato della somma è pari a "+str(somma))

inserisci un primo numero a tua scelta: 3
inserisci un secondo numero a tua scelta: 4
il risultato della somma è pari a 7.0
